### ISSUE TITLE
Add check for prohibiting t.Fatal

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-govet#1]
Given that Mattermost is migrating the code base to use `testify` it would be great to have a linter that checks that `t.Fatal` it not used anywhere.

**Comment by jespino** [comment]
That linter already exists, but is not globally applied yet because we need to fix certain cases. I'm working on it.

Anyway, thanks for the idea, keep them coming, I'm really glad to add this kind of things to the mattermost govet.

**Comment by jespino** [comment]
I going to close it as far as is already implemented, but I'll keep working on activating it on the CI as soon as is possible.
